import Config

# Configure your database
config :editor, Editor.Repo,
  username: "postgres",
  password: "password",
  hostname: "localhost",
  database: "editor_dev",
  port: 5433,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :editor, EditorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ovPuCA4vd9SjbZzYnLn0UkNkucOMEs9qM4i2gSJHdKH8aB3HUcn7tiEV98Ci4Wez",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:editor, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:editor, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :editor, EditorWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/editor_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :editor, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

s3_access_key_id =
  System.get_env("S3_ACCESS_KEY_ID") || ""

s3_secret_access_key =
  System.get_env("S3_SECRET_ACCESS_KEY") || ""

s3_bucket_name =
  System.get_env("S3_BUCKET_NAME") ||
    """
    S3 Bucket name is missing
    """

s3_bucket_region =
  System.get_env("S3_BUCKET_REGION") ||
    """
    S3 Bucket Region is missing
    """

config :editor,
  s3_access_key_id: s3_access_key_id,
  s3_secret_access_key: s3_secret_access_key,
  s3_bucket_name: s3_bucket_name,
  s3_bucket_region: s3_bucket_region

config :ex_aws,
  json_codec: Jason,
  access_key_id: s3_access_key_id,
  secret_access_key: s3_secret_access_key

config :ex_aws, :s3,
  scheme: "https://",
  host: "#{s3_bucket_region}.digitaloceanspaces.com",
  region: s3_bucket_region
